<div class="category_fillter">
    <h1><?php echo 'Filters'; ?></h1>
    <ul class="filter_navigation">
        <?php 
        $catids = $block->getBrandProducts();
        $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        foreach($catids as $key=>$value){
        	$category = $_objectManager->create('Magento\Catalog\Model\Category')->load($value);
        	$children = $category->getAllChildren(true);
            $cat_url = $block->getCategoryurl($value); ?>
        	<li class="filter_list">
        		<?php /* if(!empty($category->hasChildren())){ ?>
        			<a href="#">
        			    <?php echo $category->getName(); ?>
        		    </a>
        		<?php }else{ */ ?>
        	    	<a href="<?php echo $cat_url; ?>">
        		        <?php echo $category->getName(); ?>
        		    </a>
        	    <?php #} ?>
        	</li>
        <?php } ?>
    </ul>
</div>


  