<?php 
$brands_logos = $block->getBrandcollection();
$count = $brands_logos->getSize();
$mediaUrl = $block->getImageMediaPath();
if($count> 0): ?>
<div class="brands-container">
	<ul id="brand_slider" class="owl-carousel owl-theme owl-loaded owl-drag">
        <?php foreach($brands_logos as $brand){
	        $image = $brand->getFilename(); 
	        $link = $brand->getOptionlabel(); 
	        $str = strtolower($link); ?>
		    <li class="item">
		        <a href = "<?php echo $str; ?>">
		    		<img width="200px" src = "<?php echo $mediaUrl.$image; ?> ">
		        </a>
		    </li>
	    <?php } ?>
	</ul>
</div>
<?php endif; ?>