<?php  
	$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$registry = $objectManager->get('\Magento\Framework\Registry');
	$media_url = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	$brand = $registry->registry('current_brand');
	$image = $brand->getFilename();
?>
<div class="brand-info">
    <img src = "<?php echo $media_url.$image; ?> ">
</div>
<div class="brand-product-list">
    <?php echo $this->getProductListHtml(); ?>
</div>