<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>	
<small class="copyright">
    <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span><span> | Theme Designed & Developed by : <a href="https://www.dotsquares.com/" target="_blank"><img class="ds_loog" src="<?php echo $this->getViewFileUrl('images/ds_logo.png'); ?>" alt="Dotsquares">Dotsquares Ltd.</a>
	</span>
</small>
