<?php
/** @var $block \Dotsquares\Marketplace\Block\Search */
/** @var $helper \Magento\Search\Helper\Data */

$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-content">
        <form class="form minisearch" action="<?php echo $block->getSearchPostUrl() ?>" method="get">
            <div class="control">
			    <select name="cat" id="category_search_field">
                    <option value="">-- Any Category --</option>
				    <?php echo $block->getParentscat(); ?>
                </select>
                <input id="search" type="text" name="name" value="<?php if(isset($_GET['name'])){echo $_GET['name'];} ?>" placeholder="<?php echo __('Search entire store here...'); ?>" class="input-text"/>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
