<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
            <?= $block->getBlockHtml('header.additional') ?>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>

<?php endswitch; ?>

<?php
$design_helper = $this->helper('Dotsquares\Marketplace\Helper\Data');
$stickyheader = $design_helper->getConfig('marketplace_settings/header/sticky_header');
if($stickyheader == 1):
?>
<script>
	require([
	    'jquery',
		'mage/mage'
	], function($){
		$(document).ready(function(){
			$(window).scroll(function () {
                if( $(window).scrollTop() > $('.sections.nav-sections').offset().top && !($('.sections.nav-sections').hasClass('sticky'))){
                    $('.sections.nav-sections').addClass('sticky');
                } else if ($(window).scrollTop() == 0){
                    $('.sections.nav-sections').removeClass('sticky');
                }
            });
		});
	});
</script>

<?php endif; ?>