<?php 
$bannercollection = $block->getBannerCollection();
$_helper = $this->helper('Dotsquares\Homepageslider\Helper\Data');
$baseurl = $_helper->getBaseUrl();
$mediaUrl = $_helper->getBaseMediaUrl();
?>
<div class="banner_images">
	<ul id="banner-carousel" class="owl-carousel">
        <?php foreach($bannercollection as $banner):
			    $banner_content = $banner->getContent();
                $count = strlen($banner_content);
				if($count < 100){
                	$banner_content = substr($banner_content,0,199).'....';
                }?>
			
		        <li class="item">
		    		<img src = "<?php echo $mediaUrl.$banner->getFilename(); ?> ">
					<?php /* <div class="banner-overlay">
                        <h1><?php echo $banner->getName(); ?></h1>
                        <p><?php echo $banner_content; ?></p>
                        <a class="shop-now" href = "<?php echo $baseurl.$banner->getWeblink(); ?>">shop now</a>
                    </div> */ ?>
		    	</li>
	    <?php endforeach; ?>
	</ul>
</div>
<script>
require([
        'jquery',
        'dotsquares/marketplace',
    ], function ($) {
        $("#banner-carousel").owlCarousel({
			items:1,
			slideSpeed : 1000,
			navigation: true,
			dots:false,
			nav: true,
			loop:true
        });
		$( ".owl-prev").html('<i class="fa fa-angle-left" aria-hidden="true"></i>');
        $( ".owl-next").html('<i class="fa fa-angle-right" aria-hidden="true"></i>');
    });
</script>