<?php $blog_collection = $block->getBlogCollection();
	$blog_image = $block->getImageMediaPath(); ?>
<div class="blog">
	<ul class="blog_ul">
		<?php foreach($blog_collection as $blog){?>
			<li class="blog_listing">
				<?php $logo = $blog->getLogo();
					if($logo){
						$image = $block->getimageResize($logo,300,300);	?>
						<div class="blog_content">
							<img src ="<?php echo $image; ?>" title="<?php echo $blog->getName(); ?>" />
						</div>
					<?php } ?>
				<div class="title">
					<h1 class="blog_name"><?php echo $blog->getName(); ?></h1>
					<p class="blog_short_description">
						<?php echo $blog->getShortDescription().'.....'; ?>
						<a href="<?php echo 'blog/index/postview/id/'.$blog->getId();?>"><?php echo 'Read More' ?></a>
					</p>
					<p class="blog_devloper">
						<span class="devloper">
							<?php echo 'Create By:' ?>
						</span>
						<span class="devloper">
							<?php echo $blog->getDevloper(); ?>
						</span>
						<span class="devloper">
							<?php echo $blog->getCreatedTime(); ?>
						</span>
					</p>
				</div>
			</li>
		<?php }?>
	</ul>
</div>	