<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$enable_frontend = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('blog/general/enable_frontend');
if($enable_frontend == 1):
    $blog_collection = $block->getBlogCollection();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseurl = $storeManager->getStore()->getBaseUrl();
    $count = $blog_collection->getSize();
    if($count > 0):
    	$blog_image = $block->getImageMediaPath(); ?>
    <div class="home_blog">
    	<h2 class="main-heading">
    	 <?php echo '<span>from the <i>blog</i></span>';?>
    	</h2>
    	<ul id="blog_slider" class="owl-carousel">
    		<?php foreach($blog_collection as $blog){?>
    			<li class="blog_listing">
    				<?php $logo = $blog->getLogo();
    					$image = $block->getimageResize($logo,536,288);	?>
    					<a href="<?php echo $baseurl.'blog/index/postview/id/'.$blog->getId()?>">
    					    <img src ="<?php echo $image; ?>" title="<?php echo $blog->getName(); ?>" />
    					</a>
    			</li>
    		<?php }?>
    	</ul>
    </div>	
    <script>
    require([
            'jquery',
            'dotsquares/marketplace',
        ], function ($) {
            $("#blog_slider").owlCarousel({
    			loop:true,
                margin:10,
    			nav: true,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                        nav:true
                    },
    				1000:{
                        items:2,
                        nav:true,
                        loop:false
                    }
                }
            });
    		$( ".owl-prev").html('<i class="fa fa-angle-left" aria-hidden="true"></i>');
            $( ".owl-next").html('<i class="fa fa-angle-right" aria-hidden="true"></i>');
        });
    </script>
<?php endif;
endif; ?>