<?php $blog_collection = $block->getBlogCollection();
	$blog_image = $block->getImageMediaPath();
	#echo $blog_image;
	
#die("tets");
?>
	<div class="sider_blog">
		<div class="owl-carousel owl-theme">
			<?php foreach($blog_collection as $blog){
				$logo = $blog->getLogo();
				if($logo)
				{
					$image = $block->getimageResize($logo,300,300);	?>
					<div class="item">
						<img src ="<?php echo $image; ?>" title="<?php echo $blog->getName(); ?>"/>
						<a href="<?php echo 'index/postview/id/'.$blog->getId();?>"><?php echo 'Read More' ?></a>
					</div>
			<?php } 
			}?>
		</div>	
	</div>	
<script>
require([
        'jquery',
        'dotsquares/blog',
    ], function ($) {
        $(document).ready(function () {
            $(".owl-carousel").owlCarousel({
				singleItem : true,
				slideSpeed : 1000,
				navigation: true,
				pagination:false,
            });
			//$( ".owl-prev").html('<i class="fa fa-chevron-left"></i>');
			//$( ".owl-next").html('<i class="fa fa-chevron-right"></i>');
        });
    });
</script>