<?php 

$blog = $block->getBlogLoad();
$html = $block->getCmsFilterContent($blog->getFilename());
?>
<div class="blog_page">
	<div class="banner_image">
		<?php echo $html; ?>
	</div>
	<div class="title">
		<h1 class="blog_name"><?php echo $blog->getName(); ?></h1>
		<p class="blog_blog_devloper">
			<span class="devloper">
				<?php echo 'Create By:' ?>
			</span>
			<span class="devloper">
				<?php echo $blog->getDevloper(); ?>
			</span>
			<span class="devloper">
				<?php echo $blog->getCreatedTime(); ?>
			</span>
		</p>
		<p class="blog_blog_short_description">
			<?php echo $blog->getDescription(); ?>
		</p>
	</div>
</div>
	<div class="customer_review_box">
		<div class="customer_tilte">
			<p id="customer_comment_tilte" class="customer_title"><?php echo 'Post Your Comment';?></p>
		</div>
		<div class="customer_review_box_tab">
			<div class="customer_review_comment">
				<form id="customer_review" data-hasrequired="<?php echo ('* Required Fields')?>" data-mage-init='{"validation":{}}' class="customer_review form" >
					<div class="field name required">
						<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
						<div class="control">
							<input type="hidden" name="blogid" value="<?php echo $blog->getId()?>">
							<input name="customername" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
						</div>
					</div>
					<div class="field email required">
						<label class="label" for="email">
							<span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
						</label>
						<div class="control">
							<input name="customeremail" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
						</div>
					</div>
					<div class="field comment required">
						<label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
						<div class="control">
							<textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
						</div>
					</div>
					<div class="actions-toolbar">
						<div class="primary">
							<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
								<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
							</button>
						</div>
					</div>
				</form>
				<div class="customer_review_list">
                    <ul class="ccustomer_review">
			    		<?php $customer_review = $block->getReviewCollection();
						//echo '<pre>'; print_r($customer_review->getData());die("testt");
						foreach($customer_review as $review){
			    				?>
			    			<li class="review_content">
								<h3>Customer Reviews</h3>
							    <p class="customer_comment"><span>Comment: </span><span>"</span><?php echo $review->getComment();?><span>"</span></p>
			    				<p class="customer_detail">
			    					<span class="blog_customer">
			    						<?php echo 'Review By:';?>
			    					</span>
			    					<span class="blog_customer">
			    						<?php echo $review->getCustomername();?>
			    					</span>
			    				</p>
			    			</li>
			    		<?php
			    		}?>
			    	</ul>	
			    </div>
			</div>
		</div>
	</div>	
<script>

require([
     'jquery',
	 'mage/mage',
	 'mage/validation'
    ],
    function($) {
		var dataForm = $('#customer_review');
		dataForm.mage('validation', {});
		$("#customer_review").submit(function(e) {
		    if (dataForm.validation() && dataForm.validation('isValid')){
		        var body = $('body').loader();
                body.loader('show');
		        $.ajax({
		        	type: "POST",
		        	url: '<?php echo $this->getUrl('blog/index/sumitreview')?>',
		        	data: $("#customer_review").serialize(),
		        	success: function(data)
		        	{
		        		body.loader('hide');
		        		$('body').scrollTop(100);
						$("#customer_review")[0].reset();
		        	}
		        });
		        e.preventDefault();
		    }
		});
	}
);
</script>