<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productcollection = $block->getCollection();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
$count = count($productcollection);
if($count > 0): ?>
<div class= "bestseller_product_slider">
	<h2 class="main-heading">
		<span><?php echo "Best Seller";?></span>
	</h2>
	<div class="bestseller_product_content">
		<ul id="bestseller-carousel" class="owl-carousel">
	        <?php foreach($productcollection as $key=>$product_id): 
			    $_product = $block->getLoadProduct($product_id);
			    /* $_product = $objectManager->get('Magento\Catalog\Model\Product')->load($product_id); */
				$image_url = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize(300, 300)->getUrl();
				?>
	        	<li class="item">
	        	    <div class="beastseller_image">
						<img class="product_image" src="<?php echo $image_url; ?>" />
						<div class="overlay">
                            <ul>
								<?php $quick_view = $this->helper('\Dotsquares\Quickview\Helper\Data')->getConfig('dotsquares_quickview/general/enable');
                                if($quick_view == 1):?>
                                    <li>
								        <a class="quickview_anchor ds_quickview_button" data-quickview-url="<?php echo $block->getUrl('quickview/catalog_product/view', array('id' => $_product->getId()));  ?>" href="javascript:void(0);">									
								    	    <i class="fa fa-search" aria-hidden="true"></i>
								        </a>
								    </li>
								<?php endif; ?>
                                <li>
									<a href="#"
                                        class="action tocompare"
                                        title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                        aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                        data-post='<?php echo $this->helper('\Magento\Catalog\Helper\Product\Compare')->getPostDataParams($_product); ?>'
                                        role="button">
										<i class="fa fa-refresh" aria-hidden="true"></i>
									</a>
								</li>
                                <li>
									<a href="#" 
										   class="action towishlist"
										   title="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Wishlist')); ?>"
										   data-post='<?php echo $this->helper('\Magento\Wishlist\Helper\Data')->getAddParams($_product); ?>'
										   data-action="add-to-wishlist"
										   role="button">
										<i class="fa fa-heart-o" aria-hidden="true"></i>
									</a>
								</li>
                            </ul>
                        </div>
					</div>
					<div class="price_label">
						<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(number_format($_product->getPrice(),2),true,false); ?>
						<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
					</div>
					<div class="product_name">
						<a href = "<?php echo $_product->getProductUrl() ?>">
							<?php echo $_product->getName() ?>
						</a>
					</div>
					<div class="product-item-inner">
						<div class="actions-primary">
							<?php if ($_product->isSaleable()): ?>
								<?php $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId()]);	?>
								<?php echo $block->getBlockHtml('formkey')?>
									<button class="action tocart primary"
                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
										<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
							<?php else: ?>
								<?php if ($_product->getIsSalable()): ?>
									<div class="stock available"><span><?php echo __('In stock') ?></span></div>
								<?php else: ?>
									<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
								<?php endif; ?>
							<?php endif; ?>
						</div>
					
					</div>
					
	        	</li>
	        <?php endforeach; ?>
        </ul>
	</div>
</div>
<script>
require([
        'jquery',
        'dotsquares/marketplace',
    ], function ($) {
        $("#bestseller-carousel").owlCarousel({
			items:4,
			slideSpeed : 1000,
			nav: true,
			dots:false,
			margin:30,
			responsiveClass:true,
            responsive:{
                0:{
                    items:1,
                    nav:true
                },
				400:{
                    items:2,
                    nav:true
                },
                600:{
                    items:3,
                    nav:false
                },
                768:{
                    items:4,
                    nav:false
                },
                1000:{
                    items:5,
                    nav:true,
                    loop:false
                }
            }
        });
		$( ".owl-prev").html('<i class="fa fa-angle-left" aria-hidden="true"></i>');
        $( ".owl-next").html('<i class="fa fa-angle-right" aria-hidden="true"></i>');
    });
</script>
<?php endif; ?>